### ISSUE TITLE
ARCH_FLAGS: unbound variable

### ISSUE THREAD

**Issue by natedogs911** [cloudera/native-toolchain#23] opened 2017-07-28 22:02 UTC
Hello,

Getting the below error when running on my mac with:
`SYSTEM_GCC=1 DEBUG=1 ./buildall.sh`

./init-compiler.sh: line 41: ARCH_FLAGS: unbound variable

mac os:
10.12.5 (16F73)

Any help would be appreciated.

Thanks

**Comment by timarmstrong** [comment] 2017-07-28 22:40
Unfortunately the Mac OS X support has bit-rotted to a large extent - we don't have any automated test. It's probably possible to fix but nobody has stepped forward to do the work as of now.

**Comment by natedogs911** [comment] 2017-07-28 23:40
I don't want to beat a dead issue, but I don't mind slogging through the process of making it work on mac again. unless no one cares in which case i will make it work for myself.

I think this error is likely due to `ARCH_FLAGS` being referenced before being defined.
[on this line](https://github.com/cloudera/native-toolchain/blob/master/init-compiler.sh#L41)

on other OS types the variable is being initialized with the values for that OS, however the darwin elif statement references the variable in the initialization of itself.

I check for the variable being in any other scripts and it's not created before this point. i simply added `ARCH_FLAGS=''` to the top of the script and it's building now.

If you'd like me to put in a PR i don't mind, otherwise you can keep this issue closed as i have no doubt there are other issues that will need to be worked through.

**Comment by timarmstrong** [comment] 2017-07-29 03:45
I shouldn't have closed it so quickly. Contributions are definitely welcome.

We use gerrit for code reviews. The process is essentially the same as for impala, except you submit to the native-toolchain project: https://cwiki.apache.org/confluence/display/IMPALA/Using+Gerrit+to+submit+and+review+patches https://gerrit.cloudera.org/#/admin/projects/native-toolchain

**Comment by timarmstrong** [comment] 2017-08-04 15:59
@natedogs911 were you still interested in doing that PR?

**Comment by natedogs911** [comment] 2017-08-04 17:16
Yes @timarmstrong 
Here's a few options:
1. I can submit a PR for the quick fix to the problem i opened the issue for, and then another PR when i can work out any other blockers to building it on a mac.

2. I can leave this issue open while i go through that process.

let me know what you'd like

**Comment by mjacobs** [comment] 2017-08-04 17:24
I think the first makes sense. Thank you for contributing!

**Comment by vserrao** [comment] 2017-10-13 04:04
Has a PR been submitted for this issue ? If not, then i can take it up.  Please let me know.

**Comment by timarmstrong** [comment] 2017-10-17 03:22
Nope we didn't get a patch submitted.

**Comment by timarmstrong** [comment] 2017-10-17 03:22
So please send in a patch if you have a fix!

**Comment by vserrao** [comment] 2017-10-17 07:26
@timarmstrong Sure. I will.

**Comment by vserrao** [comment] 2017-10-17 10:22
@natedogs911 I wonder if you are still working on this. Please let me know if you are planning to raise a PR anytime sooner.

I have a different solution, though. I've also implemented it and will run a test build. I think running a build on x86 would also suffice as the issue(though found on Mac) looks to be generic i.e. the issue is not related to Mac OS fundamentals.
@timarmstrong Let we know if you think otherwise.

**Comment by timarmstrong** [comment] 2017-10-19 16:27
That sounds reasonable to me

**Comment by vserrao** [comment] 2017-10-24 03:45
The fix is merged to the master [()]( https://github.com/cloudera/native-toolchain/commit/cf2424295f1d20037efa6fc5526fd736d6a80aa5)

@timarmstrong Thanks for reviewing!

**Closed** 2019-05-08 00:18 UTC
